Vicaria.WebUI/Controllers/BusquedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;
using Vicaria.WebUI.Models;
using System.Collections.Specialized;
using System.Diagnostics;

namespace Vicaria.WebUI.Controllers
{
    public class BusquedaController : Controller
    {

        private IBusquedasRepository repository;
        public int PageSize = 10; //tamaño de página de la grilla de postulantes

        public BusquedaController(IBusquedasRepository repo)
        {
            repository = repo;
        }

        public ActionResult ListaBusquedas(int id, string nombre, int page = 1)
        {
            ViewBag.Categorias = new SelectList(repository.Categorias, "CategoriaId", "Descripcion");
            ViewBag.Jornadas = new SelectList(repository.JornadasLaborales, "JornadaLaboralID", "Descripcion");
            BusquedasListViewModel model = new BusquedasListViewModel
            {
                busquedas = repository.Busquedas
                    .Where(b => b.PostulanteID == id)
                    .OrderBy(b => b.BuscaDesde)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                idActual = id,
                nombreActual = nombre,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Busquedas.Where(b => b.PostulanteID == id).Count()
                }
            };
            return View(model);
        }

        public ViewResult Crear(int idPostulante, string nombrePostulante)//paso el postulante dueño de la busqueda
        {
            ViewBag.Categorias = new SelectList(repository.Categorias, "CategoriaId", "Descripcion");
            ViewBag.Jornadas = new SelectList(repository.JornadasLaborales, "JornadaLaboralID", "Descripcion");
            ViewBag.Postulante = nombrePostulante;
            Busqueda busqueda = new Busqueda();
            busqueda.PostulanteID = idPostulante;
            busqueda.BuscaDesde = DateTime.Today;
            busqueda.Postulante = repository.getPostulante(idPostulante);
            busqueda.BusquedaActiva = true;
            return View("Editar", busqueda);
        }

        public ViewResult Borrar(int Id)
        {
            Busqueda busqueda = repository.Busquedas.FirstOrDefault(p => p.BusquedaID == Id);
            return View(busqueda);
        }

        [HttpPost]
        public ActionResult Borrar(Busqueda busqueda)
        {
            Busqueda busquedaBorrada = repository.BorrarBusqueda(busqueda.BusquedaID);
            if (busquedaBorrada != null)
            {
                TempData["message"] = string.Format("una búsqueda  fué borrada");
            }
            string nya = busqueda.Postulante.Apellido + " " + busqueda.Postulante.Nombre;
            return RedirectToAction("ListaBusquedas", new { id = busqueda.PostulanteID, nombre = nya, page = 1 });
        }


        public ViewResult Editar(int Id)
        {
            ViewBag.Categorias = new SelectList(repository.Categorias, "CategoriaId", "Descripcion");
            ViewBag.Jornadas = new SelectList(repository.JornadasLaborales, "JornadaLaboralID", "Descripcion");
            Busqueda busqueda = repository.Busquedas.FirstOrDefault(p => p.BusquedaID == Id);
            return View(busqueda);
        }

        [HttpPost]
        public ActionResult Editar(Busqueda busqueda)
        {
            ViewBag.Categorias = new SelectList(repository.Categorias, "CategoriaId", "Descripcion");
            ViewBag.Jornadas = new SelectList(repository.JornadasLaborales, "JornadaLaboralID", "Descripcion"); 
            Postulante postulante = repository.getPostulante(busqueda.PostulanteID);
            ViewBag.Nombre = postulante.Apellido + ", " + postulante.Nombre;
            busqueda.Categoria = repository.getCategoria(busqueda.CategoriaID);
            busqueda.JornadaLaboral = repository.getJornadaLaboral(busqueda.JornadaLaboralID);
            busqueda.Postulante = postulante;
            TryUpdateModel(busqueda);
            ModelState.Clear();
            try
            {
                ValidateModel(busqueda);
            }
            catch (Exception ex)
            {
                Trace.TraceInformation("Problema: {0} ********* Mensaje: {1}", ex.ToString(), ex.Message.ToString());
            }
            if (ModelState.IsValid)
            {
                repository.GrabarBusqueda(busqueda);
                TempData["message"] = string.Format("La búsqueda de {0} fué grabado corretamente", ViewBag.Nombre);
                return RedirectToAction("ListaBusquedas", new { id = busqueda.PostulanteID, nombre = ViewBag.Nombre });
            }
            else
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);

                foreach (var error in errors)
                {
                    
                        Trace.TraceInformation("Problema: {0} Mensaje: {1}", error.Exception, error.ErrorMessage);
                }
                //algo salio malo en os datos
                return View(busqueda);
            }
        }
    }
}

Vicaria.WebUI/Controllers/OfertaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;
using Vicaria.WebUI.Models;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Diagnostics;

namespace Vicaria.WebUI.Controllers
{
    public class OfertaController : Controller
    {

        private IOfertasRepository repository;
        public int PageSize = 100; //tamaño de página de la grilla de postulantes

        public OfertaController(IOfertasRepository repo)
        {
            repository = repo;
        }

        public ActionResult ListaOfertas(int id, string nombre, int page = 1)
        {

            OfertasListViewModel model = new OfertasListViewModel
            {
                Ofertas = repository.Ofertas.Include(e=> e.Entrevistas.Select(p => p.Postulantes))
                    .Where(b => b.EmpleadorID == id)
                    .OrderBy(b => b.OfertaDesde)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize).ToList(),
                idActual = id,
                nombreActual = nombre,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Ofertas.Where(m => m.EmpleadorID == id).Count()
                }
            };
            return View(model);
        }

        

        public ActionResult BuscarOfertas(int JornadaLaboralID, string sexo, int CategoriaID, int page = 1)
        {
            
            
            OfertasListViewModel model = new OfertasListViewModel
            {
                Ofertas = repository.Ofertas.Include(e => e.Entrevistas.Select(p => p.Postulantes))
                    .Where(b => b.Sexo == sexo && b.JornadaLaboralID == JornadaLaboralID && b.CategoriaID == CategoriaID)
                    .OrderBy(b => b.OfertaDesde)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Ofertas.Include(e => e.Entrevistas.Select(p => p.Postulantes)).Where(b => b.Sexo == sexo && b.JornadaLaboralID == JornadaLaboralID && b.CategoriaID == CategoriaID).Count()
                }
            };

            ViewBag.sexo = sexo;
            ViewBag.categoria = repository.GetCategoriaDescripcion(CategoriaID);
            ViewBag.jornada = repository.GetJornadaDescripcion(JornadaLaboralID);
            return View(model);
           
        }


        public ActionResult ListaOfertasEmpleador(int idEmpleador, string nombre, int page = 1)
        {

            OfertasListViewModel model = new OfertasListViewModel
            {
                Ofertas = repository.Ofertas
                    .Where(b => b.EmpleadorID == idEmpleador)
                    .OrderBy(b => b.OfertaDesde)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize).ToList(),
                idActual = idEmpleador,
                nombreActual = nombre,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Ofertas.Where(m=> m.EmpleadorID == idEmpleador).Count()
                }
            };
            
            return View("ListaOfertas", model);
        }

        public ActionResult CrearEntrevista( int idOferta, int idBusqueda)
        {
            Entrevista entrevista = repository.GetEntrevista(idOferta, idBusqueda);
            Busqueda busqueda = repository.GetBusqueda(idBusqueda);
            if (entrevista == null)
            {
                entrevista = new Entrevista();
                entrevista.fechaAlta = DateTime.Today;
                entrevista.BusquedaID = idBusqueda;
                entrevista.Busqueda = repository.GetBusqueda(idBusqueda);
                entrevista.OfertaID = idOferta;
                entrevista.Oferta = repository.GetOferta(idOferta);
                entrevista.cubreVacante = false;
                entrevista.PostulanteId = busqueda.PostulanteID;
                repository.GrabarEntrevista(entrevista);

                //Empleador empleador = repository.getEmpleador(idEmpleador);
                TempData["message"] = string.Format("La entrevista entre {0}  y {1} fué grabada corretamente", entrevista.Oferta.Empleador.Apellido, entrevista.Busqueda.Postulante.Apellido);
            }
            else
            {
                TempData["Message"] = string.Format("La entrevista no se dió de alta por que ya existe ");
            }
            
            return RedirectToAction("Enlazar", new { id = idOferta });
            
        }
        public ViewResult Crear(int idEmpleador, string nombreEmpleador)//paso el empleador dueño de la busqueda
        {
            ViewBag.Categorias = new SelectList(repository.Categorias, "CategoriaId", "Descripcion");
            ViewBag.Jornadas = new SelectList(repository.JornadasLaborales, "JornadaLaboralID", "Descripcion");
            ViewBag.Tareas = new SelectList(repository.Tareas, "TareaID", "Descripcion");
            ViewBag.Contrataciones = new SelectList(repository.Contrataciones, "ContratacionID", "Descripcion");
            // borrar ViewBag.Edades = new SelectList(repository.Edades, "EdadId", "Rango");
            ViewBag.Estudios = new SelectList(repository.EstudiosCursados, "EstudioCursadoID", "Descripcion");
            ViewBag.Postulante = nombreEmpleador;
            Empleador empleador = repository.getEmpleador(idEmpleador);
            Oferta oferta = new Oferta();
            oferta.EmpleadorID = idEmpleador;
            oferta.Empleador = empleador;
            oferta.OfertaDesde = DateTime.Today;
            oferta.OfertaActiva = true;
            //oferta.Tareas = new List<Tarea>();
            //var tareaDefault = repository.Tareas.FirstOrDefault();
            //oferta.Tareas.Add(tareaDefault);
            //SinTareasEnOferta(oferta);

            return View("Editar", oferta);
        }

        public ActionResult Desctivar(int id)
        {
            Oferta oferta = repository.Ofertas.FirstOrDefault(p => p.OfertaID == id);
            oferta.OfertaActiva = false;
            repository.GrabarOferta(oferta);

            return RedirectToAction("ListarEntrevistasVencidas", "Entrevista");

           
        }

        public ViewResult Editar(int Id)
        {
            ViewBag.Categorias = new SelectList(repository.Categorias, "CategoriaId", "Descripcion");
            ViewBag.Jornadas = new SelectList(repository.JornadasLaborales, "JornadaLaboralID", "Descripcion");
            ViewBag.Contrataciones = new SelectList(repository.Contrataciones, "ContratacionID", "Descripcion");
            // borrar  ViewBag.Edades = new SelectList(repository.Edades, "EdadId", "Rango");
            ViewBag.Estudios = new SelectList(repository.EstudiosCursados, "EstudioCursadoID", "Descripcion");
            Oferta oferta = repository.Ofertas.FirstOrDefault(p => p.OfertaID == Id);
            //SinTareasEnOferta(oferta);
            return View(oferta);
        }

        public ViewResult Enlazar(int id)
        {
            Oferta ofertaActual = repository.GetOferta(id);
            //List<Postulante> postulantes = new List<Postulante>();  estuve cambiando el postulante por la busqueda
            List<Busqueda> busquedasEncontradas = new List<Busqueda>();
            

            var busquedas = repository.Busquedas.Where(b => b.BusquedaActiva == true && b.CategoriaID == ofertaActual.CategoriaID 
                            && b.JornadaLaboralID == ofertaActual.JornadaLaboralID
                            && b.Postulante.sexo == ofertaActual.Sexo);
            foreach(Busqueda  busqueda in busquedas)
            {
                Postulante postulante = repository.getPostulante(busqueda.PostulanteID);
                // borrar Edad edad = repository.getEdad(ofertaActual.EdadID);
                int edadMin = ofertaActual.EdadMin;
                int edadMax = ofertaActual.EdadMax;
                DateTime fechaDeHoy = DateTime.Now;
                int anioDeHoy = fechaDeHoy.Year;
                int anioDePostulante = (postulante.FechaDeNacimiento).Year;
                int edadActual = anioDeHoy - anioDePostulante;
                if (edadMin <= edadActual && edadMax >= edadActual )
                    busquedasEncontradas.Add(busqueda);
            }
            EnlacesPosiblesListViewModel model = new EnlacesPosiblesListViewModel
            {
                busquedasPosibles = busquedasEncontradas,
                oferta = ofertaActual,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = 1,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Ofertas.Where(m => m.EmpleadorID == id).Count()
                }
            };
            return View(model);
        }



        //private void SinTareasEnOferta(Oferta oferta)
        //{
        //    var todasLasTareas = repository.GetTareas;// carga todas las tareas disponibles en la base
        //    var ofertaTareas = repository.TareasEnOferta(oferta); //carga las tareas de la oferta corriente
        //    var viewModel = new List<TareasDeOfertaListViewModel>();
        //    foreach (var tarea in todasLasTareas)
        //    {
        //        viewModel.Add(new TareasDeOfertaListViewModel
        //        {

Vicaria.WebUI/Views/Oferta/BuscarOfertas.cshtml
@using Vicaria.WebUI.HtmlHelpers;
@model Vicaria.WebUI.Models.OfertasListViewModel

@{
    ViewBag.Title = "Ofertas  de Empledores";
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría</a>
    <ul class="nav navbar-nav">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <input type="submit" value="Home" class="btn btn-default btn-lg ">
            }
        </li>
        <li>
            @using (Html.BeginForm("List", "Postulante"))
            {
                <input type="submit" value="Postulantes" class="btn btn-success btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("List", "Empleador"))
            {
                <input type="submit" value="Empleadores" class="btn btn-primary btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("ListarEntrevistas", "Entrevista"))
            {
                <input type="submit" value="Entrevistas" class="btn btn-warning btn-lg" />
            }

        </li>

    </ul>

</div>


    <div>
        <h2>Listado de ofertas de empleadores</h2>
        @*<a href="@Url.Action("Crear", "Oferta", new { idEmpleador = Model.idActual, nombreEmpleador = Model.nombreActual })" class="btn"><span class="glyphicon glyphicon-plus-sign"></span></a>*@
        <p>
            @*<b> @Html.DisplayNameFor(model => model.Ofertas.First().Categoria): </b>  @Html.DisplayFor(m => m.Ofertas.First().Categoria.Descripcion) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;*@
            <b> Categoria: </b>  @ViewBag.categoria &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <b>jornada:</b> @ViewBag.jornada  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <b>Sexo :</b> @ViewBag.sexo
        </p>
    </div>
@if (!Model.Ofertas.Any())
{
    <tr><td>No exiten resultados para esta búsqueda</td></tr>
}
else
{
    <table class="table table-condensed" style="border-collapse:collapse;">
        <thead>
            <tr>
                <th>Empleador</th>
                <th>Vacantes</th>
                <th>Oferta Desde</th>
                <th>Activa</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var oferta in Model.Ofertas)
            {
                <tr data-toggle="collapse" data-target="#@oferta.OfertaID" class="accordion-toggle">
                    <td>@oferta.Empleador.Apellido, @oferta.Empleador.Nombre</td>
                    <td>@oferta.Vacantes</td>
                    <td>@oferta.OfertaDesde.ToString("dd/MM/yyyy")</td>
                    <td>
                        <div class="display-label" style="font-weight: normal">
                            @if (oferta.OfertaActiva)
                            {
                                <p>Si</p>
                            }
                            else
                            {
                                <p>No</p>
                            }

                        </div>
                    </td>
                    <td>
         
                        @if (oferta.OfertaActiva)
                        {
                            <a href="@Url.Action("Enlazar", "Oferta", new { id = oferta.OfertaID })" class="btn" title="Generar enlace"><span class="glyphicon glyphicon-magnet"></span></a>
                        }
                        else
                        {
                            <a href="@Url.Action("Enlazar", "Oferta", new { id = oferta.OfertaID })" class="btn" title="Generar enlace" disabled><span class="glyphicon glyphicon-magnet"></span></a>
                        }

                    </td>
                </tr>
                <tr>
                    <td colspan="5" class="hiddenRow">
                        <div class="accordian-body collapse" id="@oferta.OfertaID">
                            @if (oferta.Entrevistas.Count() == 0)
                            {
                                <p class="text-danger">No hay datos de entrevistas para esta oferta</p>
                            }
                            else
                            {
                                <table class="table table-inverse">

                                    <thead>
                                        <tr>
                                            <th class="alert-info">Apellido</th>
                                            <th class="alert-info">Nombre</th>
                                            <th class="alert-info">DNI</th>
                                            <th class="alert-info">Teléfono</th>
                                            <th class="alert-info">Celular</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var e in oferta.Entrevistas)
                                        {
                                            <tr>
                                                <td class="text-primary">
                                                    @e.Postulantes.Apellido
                                                </td>
                                                <td class="text-primary">
                                                    @e.Postulantes.Nombre
                                                </td>
                                                <td class="text-primary">
                                                    @e.Postulantes.Documento
                                                </td>
                                                <td class="text-primary">
                                                    @e.Postulantes.Telefono
                                                </td>
                                                <td class="text-primary">
                                                    @e.Postulantes.Celular
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            }
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>
}

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x }))
</div>


Vicaria.WebUI/Views/Oferta/Enlazar.cshtml
@using Vicaria.WebUI.HtmlHelpers;
@model Vicaria.WebUI.Models.EnlacesPosiblesListViewModel

@{
    ViewBag.Title = "Enlaces posibles de la oferta";
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem -  Vicaría</a>
    <ul class="nav navbar-nav">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <input type="submit" value="Home" class="btn btn-default btn-lg ">
            }
        </li>
        <li>
            @using (Html.BeginForm("List", "Postulante"))
            {
                <input type="submit" value="Postulantes" class="btn btn-success btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("List", "Empleador"))
            {
                <input type="submit" value="Empleadores" class="btn btn-primary btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("ListarEntrevistas", "Entrevista"))
            {
                <input type="submit" value="Entrevistas" class="btn btn-warning btn-lg" />
            }

        </li>
        <li>
            @using (Html.BeginForm("ListaOfertasEmpleador", "Oferta"))
            {
                @Html.Hidden("idEmpleador", Model.oferta.EmpleadorID );
                @Html.Hidden("nombre", Model.oferta.Empleador.Apellido);
                @Html.Hidden("page", Model.PagingInfo);
    <input type="submit" value="Lista de Ofertas" class="btn btn-primary btn-lg">
            }
            
        </li>
        
    </ul>

</div>


<h2>Listado de posibles enlaces para la oferta: @Html.DisplayFor(m => m.oferta.Categoria.Descripcion)</h2>
@*<a href="@Url.Action("Crear", "Oferta", new { idEmpleador = Model.idActual, nombreEmpleador = Model.nombreActual })" class="btn"><span class="glyphicon glyphicon-plus-sign"></span></a>*@
<table class="table table-striped table-condensed table-bordered">
        <tr>
            <th>Categoría</th>
            <th>Jornada</th>
            <th>Vacantes</th>
            <th>Postulante</th>
            <th>Empleador</th>
            <th>Acciones</th>
        </tr>
    @foreach (var busqueda in Model.busquedasPosibles)
    {
        <tr>
            <td>@Model.oferta.Categoria.Descripcion</td>
            <td>@Model.oferta.JornadaLaboral.Descripcion</td>
            <td>@Model.oferta.Vacantes</td>
            <td>@busqueda.Postulante.Apellido</td>
            <td>@Model.oferta.Empleador.Apellido</td>
            <td>
                <a href="@Url.Action("Detallar", "Postulante", new { id = busqueda.Postulante.PostulanteID, retorno = 1 })" class="btn" title="Ver detalle de Postulante"><span class="glyphicon glyphicon-user"></span></a> 
                <a href="@Url.Action("Detallar", "Empleador", new { id = Model.oferta.EmpleadorID, retorno = 1 })" class="btn" title="Ver detalle de Empleador"><span class="glyphicon glyphicon glyphicon-briefcase"></span></a> 
                <a href="@Url.Action("CrearEntrevista", "Oferta", new { idOferta = Model.oferta.OfertaID, idBusqueda = busqueda.BusquedaID })" class="btn" title="Generar enlace"><span class="glyphicon glyphicon-pushpin"></span></a>
            </td>
        </tr>
        
    }
</table>

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page= x}))
</div>

Vicaria.WebUI/Views/Oferta/ListaOfertas.cshtml
@using Vicaria.WebUI.HtmlHelpers;
@model Vicaria.WebUI.Models.OfertasListViewModel

@{
    ViewBag.Title = "Ofertas  de Empledores";
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría</a>
    <ul class="nav navbar-nav">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <input type="submit" value="Home" class="btn btn-default btn-lg ">
            }
        </li>
        <li>
            @using (Html.BeginForm("List", "Postulante"))
            {
                <input type="submit" value="Postulantes" class="btn btn-success btn-lg">
            }
            
        </li>
        <li>
            @using (Html.BeginForm("List", "Empleador"))
            {
                <input type="submit" value="Empleadores" class="btn btn-primary btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("ListarEntrevistas", "Entrevista"))
            {
                <input type="submit" value="Entrevistas" class="btn btn-warning btn-lg" />
            }

        </li>
        
    </ul>

</div>


<h2>Listado de ofertas de empleadores: @Html.DisplayFor(m => m.nombreActual)</h2>
<a href="@Url.Action("Crear", "Oferta", new { idEmpleador = Model.idActual, nombreEmpleador = Model.nombreActual })" class="btn"><span class="glyphicon glyphicon-plus-sign"></span></a>
@*<table class="table table-striped table-condensed table-bordered" >*@
<table class="table table-condensed" style="border-collapse:collapse;">
    <thead>
        <tr>
            <th>Categoría</th>
            <th>Jornada</th>
            <th>Vacantes</th>
            <th>Oferta Desde</th>
            <th>Activa</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var oferta in Model.Ofertas)
    {
        <tr data-toggle="collapse" data-target="#@oferta.OfertaID" class="accordion-toggle">
            <td>@oferta.Categoria.Descripcion</td>
            <td>@oferta.JornadaLaboral.Descripcion</td>
            <td>@oferta.Vacantes</td>
            <td>@oferta.OfertaDesde.ToString("dd/MM/yyyy")</td>
            <td>
                <div class="display-label" style="font-weight: normal">
                    @if (oferta.OfertaActiva)
                {
                    <p>Si</p>
            }
            else
            {
                <p>No</p>
        }

                </div>



            </td>

            <td>
                <a href="@Url.Action("Editar", "Oferta", new { id = oferta.OfertaID })" class="btn"><span class="glyphicon glyphicon-pencil"></span></a>
                @*<a href="@Url.Action("Borrar", "Busqueda", new { id = busqueda.BusquedaID })" class="btn"><span class="glyphicon glyphicon-remove-circle"></span></a>*@
                @if (oferta.OfertaActiva)
            {
                <a href="@Url.Action("Enlazar", "Oferta", new { id = oferta.OfertaID })" class="btn" title="Generar enlace"><span class="glyphicon glyphicon-magnet"></span></a>
        }
        else
        {
            <a href="@Url.Action("Enlazar", "Oferta", new { id = oferta.OfertaID })" class="btn" title="Generar enlace" disabled><span class="glyphicon glyphicon-magnet"></span></a>
    }

            </td>
        </tr>
        <tr>
            <td colspan="5" class="hiddenRow">
                <div class="accordian-body collapse" id="@oferta.OfertaID">
                    @if (oferta.Entrevistas.Count() == 0)
        {
            <p class="text-danger">No hay datos de entrevistas para esta oferta</p>
}
else
{
            <table class="table table-inverse">

                <thead>
                    <tr>
                        <th class="alert-info">Apellido</th>
                        <th class="alert-info">Nombre</th>
                        <th class="alert-info">DNI</th>
                        <th class="alert-info">Teléfono</th>
                        <th class="alert-info">Celular</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var e in oferta.Entrevistas)
        {
                    <tr>
                        <td class="text-primary">
                            @e.Postulantes.Apellido

                        </td>
                        <td class="text-primary">
                            @e.Postulantes.Nombre
                        </td>
                        <td class="text-primary">
                            @e.Postulantes.Documento
                        </td>
                        <td class="text-primary">
                            @e.Postulantes.Telefono
                        </td>
                        <td class="text-primary">
                            @e.Postulantes.Celular
                        </td>

                    </tr>

}
                </tbody>
            </table>
}
                </div>
            </td>
        </tr>
                
                }
    </tbody>
</table>

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page= x}))
</div>