Vicaria.WebUI/Controllers/EmpleadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;
using Vicaria.WebUI.Models;
using System.Collections.Specialized;
using System.Data.Entity.Validation;

namespace Vicaria.WebUI.Controllers
{
    public class EmpleadorController : Controller
    {
        private IEmpleadorRepository repository;
        public int PageSize = 100; //tamaño de página de la grilla de postulantes

        public EmpleadorController(IEmpleadorRepository empleadorRepository)
        {
            this.repository = empleadorRepository;
        }

        public ViewResult Borrar(int Id)
        {
            Empleador empleador = repository.Empleadores.FirstOrDefault(p => p.EmpleadorID == Id);
            return View(empleador);
        }

        [HttpPost]
        public ActionResult Borrar(Empleador empleador)
        {
            Empleador empleadorBorrado = repository.BorrarEmpleador(empleador.EmpleadorID);
            if (empleadorBorrado != null)
            {
                TempData["message"] = string.Format("{0} fué borrado", empleadorBorrado.Apellido);
            }
            return RedirectToAction("List");
        }

        public ViewResult Crear()
        {
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            Empleador empleador = new Empleador();
            empleador.FechaAlta = DateTime.Now;
            empleador.keepAlive = DateTime.Now;
            return View("Editar", empleador);
        }

        public ViewResult List(int page = 1)
        {
            EmpleadorListViewModel model = new EmpleadorListViewModel
            {
                Empleadores = repository.Empleadores
                    .OrderByDescending(p => p.keepAlive)
                    .Skip((page-1) * PageSize)
                    .Take(PageSize),
                    PagingInfo = new PagingInfo{
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = repository.Empleadores.Count()
                    }
            };
            return View(model);
        }

        public ViewResult Buscar( string busqueda, int page = 1) 
        {
            EmpleadorListViewModel model = new EmpleadorListViewModel();

            int dni = 0;
            bool esDni = int.TryParse(busqueda, out dni);
            
           
                if (esDni )
                {
                    model = new EmpleadorListViewModel
                    {
                        Empleadores = repository.Empleadores
                            .Where(e => e.Documento == dni)
                            .OrderByDescending(p => p.keepAlive)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize),
                        PagingInfo = new PagingInfo
                        {
                            CurrentPage = page,
                            ItemsPerPage = PageSize,
                            TotalItems = repository.Empleadores.Where(e => e.Documento == dni).Count()
                        }
                    };

                }
                else
                {
                    model = new EmpleadorListViewModel
                    {
                        Empleadores = repository.Empleadores
                            .Where(e => e.Apellido.ToUpper().Contains(busqueda.ToUpper()) || e.Nombre.ToUpper().Contains(busqueda.ToUpper()))
                            .OrderByDescending(p => p.keepAlive)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize),
                        PagingInfo = new PagingInfo
                        {
                            CurrentPage = page,
                            ItemsPerPage = PageSize,
                            TotalItems = repository.Empleadores.Where(e => e.Apellido.Contains(busqueda)).Count()
                        }
                    };


                };
             return View("List",model);



            





            }
           
       

       

        public ViewResult Editar(int Id)
        {
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            Empleador empleador = repository.Empleadores.FirstOrDefault(p => p.EmpleadorID == Id);
            return View(empleador);
        }
        
        [HttpPost]
        public ActionResult Editar(Empleador empleador)
        {
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            if (ModelState.IsValid)
            {
                repository.GrabarEmpleador(empleador);
                TempData["message"] = string.Format("{0} fué grabado corretamente", empleador.Apellido);
                return RedirectToAction("List");
            }
            else
            {
                //algo salio malo en os datos
                return View(empleador);
            }
        }

        public ViewResult Detallar(int Id, int retorno = 0)
        {

            Empleador empleador = repository.Empleadores.FirstOrDefault(p => p.EmpleadorID == Id);

            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "ID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            ViewBag.Retorno = retorno;

            return View(empleador);
        }

        public ActionResult KeepAlive(int Id)
        {
            Empleador empleador = repository.Empleadores.FirstOrDefault(p => p.EmpleadorID == Id);
            empleador.keepAlive = DateTime.Now;
            if (ModelState.IsValid)
            {
                repository.GrabarEmpleador(empleador);
                TempData["message"] = string.Format("{0} fué refrescado corretamente", empleador.Apellido);
                return RedirectToAction("List");
            }
            else
            {
                //algo salio malo en os datos
                return View(empleador);
            }
        }
    }
}

Vicaria.WebUI/Controllers/EntrevistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vicaria.WebUI.Models;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;
using System.Diagnostics;

namespace Vicaria.WebUI.Controllers
{
    public class EntrevistaController : Controller
    {
       private IEntrevistaRepository repository;
       public int PageSize = 100;

       public EntrevistaController(IEntrevistaRepository repo)
        {
            repository = repo;
        }

        public ViewResult ListarEntrevistas(int page = 1)
        {

            EntrevistasListViewModel model = new EntrevistasListViewModel
            {
                entrevistas = repository.Entrevistas
                    .OrderBy(x => x.fechaEntrevista).ThenBy(x => x.Oferta.Empleador.Apellido)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Entrevistas.Count()
                }
            };
            return View(model);
        }

        public ViewResult ListarEntrevistasVencidas(int page = 1)
        {
            DateTime fechaLimite = DateTime.Today.AddDays(-10);
            var fechaNula = new DateTime(0001, 01, 01);
            EntrevistasListViewModel model = new EntrevistasListViewModel
            {
                
            entrevistas = repository.Entrevistas
                    .Where(x => x.fechaAlta < fechaLimite && x.Oferta.OfertaActiva)
                    .OrderBy(x => x.OfertaID)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Entrevistas.Count()
                }
            };
            return View(model);
        }

        public ActionResult ListarEntrevistasDeEmpleador(int idEmpleador, int page = 1)
        {
            EntrevistasListViewModel model = new EntrevistasListViewModel
            {
                entrevistas = repository.Entrevistas
                    .Where(e => e.Oferta.EmpleadorID == idEmpleador)
                    .OrderBy(e => e.fechaAlta)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Entrevistas.Where(e => e.Oferta.EmpleadorID == idEmpleador).Count()
                }
            };
            return View(model);
        }

        public ActionResult ListarEntrevistasDePostulante(int idPostulante, int page = 1)
        {
            EntrevistasListViewModel model = new EntrevistasListViewModel
            {
                entrevistas = repository.Entrevistas
                    .Where(e => e.Busqueda.PostulanteID == idPostulante)
                    .OrderBy(e => e.fechaAlta)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Entrevistas.Where(e => e.Busqueda.PostulanteID == idPostulante).Count()
                }
            };
            return View(model);
        }


        public ActionResult Aprobar(int? id)
        {
            Entrevista entrevista = repository.Entrevistas.FirstOrDefault(p => p.entrevistaID == id);
            entrevista.cubreVacante = true;
            if (ModelState.IsValid)
            {
                repository.GrabarEntrevista(entrevista);
                TempData["message"] = string.Format("{0} fué actualizado corretamente", entrevista.Oferta.Empleador.Apellido);
                return RedirectToAction("ListarEntrevistasVencidas");
            }
            else
            {
                //algo salio malo en os datos
                return View("ListarEntrevistasVencidas");
            }
        }

        public ActionResult Desaprobar(int? id)
        {
            Entrevista entrevista = repository.Entrevistas.FirstOrDefault(p => p.entrevistaID == id);
            entrevista.cubreVacante = false;
            if (ModelState.IsValid)
            {
                repository.GrabarEntrevista(entrevista);
                TempData["message"] = string.Format("{0} fué actualizado corretamente", entrevista.Oferta.Empleador.Apellido);
                return RedirectToAction("ListarEntrevistasVencidas");
            }
            else
            {
                //algo salio malo en os datos
                return View("ListarEntrevistasVencidas");
            }
        }

        public ViewResult Editar(int Id)
        {
            Entrevista entrevista = repository.Entrevistas.FirstOrDefault(x => x.entrevistaID == Id);
            return View(entrevista);
        }

        [HttpPost]
        public ActionResult Editar(Entrevista entrevista)
        {
            Oferta oferta = repository.GetOferta(entrevista.OfertaID);
            Busqueda busqueda = repository.GetBusqueda(entrevista.BusquedaID);
            entrevista.Oferta = oferta;
            entrevista.Busqueda = busqueda;
            TryUpdateModel(entrevista);
            ModelState.Clear();
            try
            {
                ValidateModel(entrevista);
            }
            catch (Exception ex)
            {
                Trace.TraceInformation("Problema: {0} ********* Mensaje: {1}", ex.ToString(), ex.Message.ToString());
            }
            if (ModelState.IsValid)
            {
                if (entrevista.cubreVacante )
                {
                    //tengo que dar de bajala oferta y la busqueda
                    oferta.Vacantes = oferta.Vacantes - 1;
                    if (oferta.Vacantes <= 0)
                    {
                         try
                        {
                            ValidateModel(oferta);
                        }
                        catch (Exception ex)
                        {
                            Trace.TraceInformation("Problema: {0} ********* Mensaje: {1}", ex.ToString(), ex.Message.ToString());
                        }
                         if (ModelState.IsValid)
                         {
                             oferta.OfertaActiva = false;
                             repository.GrabarOferta(oferta);
                         }
                    }
                    
                    busqueda.BusquedaActiva = false;
                    repository.GrabarBusqueda(busqueda);
                }
                repository.GrabarEntrevista(entrevista);
                return RedirectToAction("ListarEntrevistas");
            }
            else
            {
                //alg salio malo en os datos
                return View(entrevista);
            }
        }

        public ViewResult Crear(int idPostulante, int idEmpleador, int idOferta)
        {
            Entrevista entrevista = new Entrevista();
            entrevista.fechaAlta = DateTime.Today;
            //entrevista.EmpleadorID = idEmpleador;
            //entrevista.PostulanteID = idPostulante;
            entrevista.cubreVacante = false;
            repository.GrabarEntrevista(entrevista);
            

            return View("EditarEntrevista");
        }

        public ViewResult BorrarEntrevista(int Id)
        {
            Entrevista entrevista = repository.Entrevistas.FirstOrDefault(p => p.entrevistaID == Id);
            return View(entrevista);
        }

        [HttpPost]
        public ActionResult BorrarEntrevista(Entrevista entrevista)
        {
            Entrevista entrevistaBorrada = repository.BorrarEntrevista(entrevista.entrevistaID);
            if (entrevistaBorrada != null)
            {
                TempData["message"] = string.Format("Una entrevista con Empleador {0} y postulante {1} fué borrada", entrevistaBorrada.Oferta.Empleador.Apellido, entrevistaBorrada.Busqueda.Postulante.Apellido);
            }
            return RedirectToAction("ListarEntrevistas");
        }
    }
}

Vicaria.WebUI/Views/Entrevista/Editar.cshtml
@model Vicaria.Domain.Entities.Entrevista
@{
    //ViewBag.Title = "Edición de " + @Model.Postulante.Apellido + ", " + @Model.Postulante.Nombre;
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría de Devoto</a>


</div>

<div class="panel">
    <div class="panel-heading">
        <h3>Editar Entrevista</h3>
    </div>
    @using (Html.BeginForm("Editar","Entrevista"))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.entrevistaID)
            @Html.HiddenFor(m => m.OfertaID)
            @Html.HiddenFor(m => m.BusquedaID)
            @Html.HiddenFor(m => m.fechaAlta)
            @Html.HiddenFor(m => m.Busqueda)
            @Html.HiddenFor(m => m.Oferta)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "entrevistaID"
                    && property.PropertyName != "OfertaID"
                    && property.PropertyName != "BusquedaID"
                    && property.PropertyName != "fechaAlta"
                    && property.PropertyName != "Busqueda"
                    && property.PropertyName != "Oferta"
                    
                    )
                {
                   <div class="form-group">
            
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                       
            
            @switch (property.PropertyName)
            {
                
                case "fechaEntrevista":
                   
                    @Html.EditorFor(model => model.fechaEntrevista)
                    break;

                case "Observaciones":
                    @Html.TextArea("Observaciones", new { rows = 10, columns = 40, style = "width:800px;" })
                    break;
                case "cubreVacante":
                    <label>@Html.RadioButton(property.PropertyName, true)Si</label>
                    <label>@Html.RadioButton(property.PropertyName, false)No</label>
                    break;
                default:
                    @Html.TextBox(property.PropertyName, null, new { @class = "form-control", style = "width:500px;"});
                    break;
            }
            @Html.ValidationMessage(property.PropertyName)
        
    </div>
                }
            }
        </div>
        <div class="panel-footer">
            
            
            <input type="submit" value="Grabar"  class="btn btn-primary" />
            <a href="@Url.Action("ListarEntrevistas", "Entrevista")" class="btn">Volver a Entrevistas <span class="glyphicon glyphicon-comment"></span></a>
        </div>
    }

        
        
        

Vicaria.WebUI/Views/Entrevista/ListarEntrevistas.cshtml
@using Vicaria.WebUI.HtmlHelpers;
@model Vicaria.WebUI.Models.EntrevistasListViewModel

@{
    ViewBag.Title = "Concertación de entrevistas";
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría</a>
    <ul class="nav navbar-nav">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <input type="submit" value="Home" class="btn btn-default btn-lg ">
            }
        </li>
        <li>
            @using (Html.BeginForm("List", "Postulante"))
            {
                <input type="submit" value="Postulantes" class="btn btn-success btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("List", "Empleador"))
            {
                <input type="submit" value="Empleadores" class="btn btn-primary btn-lg">
            }

        </li>
       
    </ul>

</div>


<h2>Listado de Entrevistas</h2>
@*<a href="@Url.Action("Crear", "Oferta", new { idEmpleador = Model.idActual, nombreEmpleador = Model.nombreActual })" class="btn"><span class="glyphicon glyphicon-plus-sign"></span></a>*@
<table class="table table-striped table-condensed table-bordered">
        <tr>
            <th>Empleador</th>
            <th>Categoria</th>
            <th>Jornada</th>
            <th>Postulante</th>
            <th>Fecha entrevista</th>
            <th>Vacante Cubierta</th>
            <th>Acciones</th>
        </tr>
    @foreach (var entrevista in Model.entrevistas)
    {
        <tr>
            <td>@entrevista.Oferta.Empleador.Apellido</td>
            <td>@entrevista.Oferta.Categoria.Descripcion</td>
            <td>@entrevista.Oferta.JornadaLaboral.Descripcion</td>
            <td>@entrevista.Busqueda.Postulante.Apellido</td>
            
            <td>@entrevista.fechaEntrevista.ToString("dd/MM/yyyy")</td>
            <td>
                <div class="display-label" style="font-weight: normal">
                    @if (entrevista.cubreVacante)
                    {
                        <p>Si</p>
                    }
                    else
                    {
                        <p>No</p>
                    }

                </div>
            </td>
            
            <td>
                <a href="@Url.Action("Editar", "Entrevista", new { id = entrevista.entrevistaID })" class="btn"><span class="glyphicon glyphicon-pencil"></span></a> 
                @*<a href="@Url.Action("Borrar", "Busqueda", new { id = busqueda.BusquedaID })" class="btn"><span class="glyphicon glyphicon-remove-circle"></span></a>*@ 
                @*<a href="@Url.Action("Enlazar", "Oferta", new { id = oferta.OfertaID })" class="btn" title="Generar enlace"><span class="glyphicon glyphicon-magnet"></span></a>*@
            </td>
        </tr>
        
    }
</table>

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("ListarEntrevistas", new { page= x}))
</div>

Vicaria.WebUI/Views/Entrevista/ListarEntrevistasDeEmpleador.cshtml
@using Vicaria.WebUI.HtmlHelpers;
@model Vicaria.WebUI.Models.EntrevistasListViewModel

@{
    ViewBag.Title = "Concertación de entrevistas";
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría</a>
    <ul class="nav navbar-nav">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <input type="submit" value="Home" class="btn btn-default btn-lg ">
            }
        </li>
        <li>
            @using (Html.BeginForm("List", "Postulante"))
            {
                <input type="submit" value="Postulantes" class="btn btn-success btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("List", "Empleador"))
            {
                <input type="submit" value="Empleadores" class="btn btn-primary btn-lg">
            }

        </li>
       
    </ul>

</div>


<h2>Listado de Entrevistas</h2>
@*<a href="@Url.Action("Crear", "Oferta", new { idEmpleador = Model.idActual, nombreEmpleador = Model.nombreActual })" class="btn"><span class="glyphicon glyphicon-plus-sign"></span></a>*@
<table class="table table-striped table-condensed table-bordered">
        <tr>
            <th>Empleador</th>
            <th>Categoria</th>
            <th>Jornada</th>
            <th>Postulante</th>
            <th>Fecha</th>
            <th>Vacante Cubierta</th>
            <th>Acciones</th>
        </tr>
    @foreach (var entrevista in Model.entrevistas)
    {
        <tr>
            <td>@entrevista.Oferta.Empleador.Apellido</td>
            <td>@entrevista.Oferta.Categoria.Descripcion</td>
            <td>@entrevista.Oferta.JornadaLaboral.Descripcion</td>
            <td>@entrevista.Busqueda.Postulante.Apellido</td>
            
            <td>@entrevista.fechaEntrevista.ToString("dd/MM/yyyy")</td>
            <td>
                <div class="display-label" style="font-weight: normal">
                    @if (entrevista.cubreVacante)
                    {
                        <p>Si</p>
                    }
                    else
                    {
                        <p>No</p>
                    }

                </div>
            </td>
            
            <td>
                <a href="@Url.Action("Editar", "Entrevista", new { id = entrevista.entrevistaID })" class="btn"><span class="glyphicon glyphicon-pencil"></span></a> 
                @*<a href="@Url.Action("Borrar", "Busqueda", new { id = busqueda.BusquedaID })" class="btn"><span class="glyphicon glyphicon-remove-circle"></span></a>*@ 
                @*<a href="@Url.Action("Enlazar", "Oferta", new { id = oferta.OfertaID })" class="btn" title="Generar enlace"><span class="glyphicon glyphicon-magnet"></span></a>*@
            </td>
        </tr>
        
    }
</table>

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page= x}))
</div>

Vicaria.WebUI/Views/Entrevista/ListarEntrevistasDePostulante.cshtml
@using Vicaria.WebUI.HtmlHelpers;
@model Vicaria.WebUI.Models.EntrevistasListViewModel

@{
    ViewBag.Title = "Concertación de entrevistas";
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría</a>
    <ul class="nav navbar-nav">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <input type="submit" value="Home" class="btn btn-default btn-lg ">
            }
        </li>
        <li>
            @using (Html.BeginForm("List", "Postulante"))
            {
                <input type="submit" value="Postulantes" class="btn btn-success btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("List", "Empleador"))
            {
                <input type="submit" value="Empleadores" class="btn btn-primary btn-lg">
            }

        </li>
       
    </ul>

</div>


<h2>Listado de Entrevistas</h2>
@*<a href="@Url.Action("Crear", "Oferta", new { idEmpleador = Model.idActual, nombreEmpleador = Model.nombreActual })" class="btn"><span class="glyphicon glyphicon-plus-sign"></span></a>*@
<table class="table table-striped table-condensed table-bordered">
        <tr>
            <th>Empleador</th>
            <th>Categoria</th>
            <th>Jornada</th>
            <th>Postulante</th>
            <th>Fecha</th>
            <th>Vacante Cubierta</th>
            <th>Acciones</th>
        </tr>
    @foreach (var entrevista in Model.entrevistas)
    {
        <tr>
            <td>@entrevista.Oferta.Empleador.Apellido</td>
            <td>@entrevista.Oferta.Categoria.Descripcion</td>
            <td>@entrevista.Oferta.JornadaLaboral.Descripcion</td>
            <td>@entrevista.Busqueda.Postulante.Apellido</td>
            
            <td>@entrevista.fechaEntrevista.ToString("dd/MM/yyyy")</td>
            <td>
                <div class="display-label" style="font-weight: normal">
                    @if (entrevista.cubreVacante)
                    {
                        <p>Si</p>
                    }
                    else
                    {
                        <p>No</p>
                    }

                </div>
            </td>
            
            <td>
                <a href="@Url.Action("Editar", "Entrevista", new { id = entrevista.entrevistaID })" class="btn"><span class="glyphicon glyphicon-pencil"></span></a> 
                @*<a href="@Url.Action("Borrar", "Busqueda", new { id = busqueda.BusquedaID })" class="btn"><span class="glyphicon glyphicon-remove-circle"></span></a>*@ 
                @*<a href="@Url.Action("Enlazar", "Oferta", new { id = oferta.OfertaID })" class="btn" title="Generar enlace"><span class="glyphicon glyphicon-magnet"></span></a>*@
            </td>
        </tr>
        
    }
</table>

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page= x}))
</div>

Vicaria.WebUI/Views/Entrevista/ListarEntrevistasVencidas.cshtml
@using Vicaria.WebUI.HtmlHelpers;
@model Vicaria.WebUI.Models.EntrevistasListViewModel

@{
    ViewBag.Title = "Entrevistas vencidas";
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría</a>
    <ul class="nav navbar-nav">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <input type="submit" value="Home" class="btn btn-default btn-lg ">
            }
        </li>
        <li>
            @using (Html.BeginForm("List", "Postulante"))
            {
                <input type="submit" value="Postulantes" class="btn btn-success btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("List", "Empleador"))
            {
                <input type="submit" value="Empleadores" class="btn btn-primary btn-lg">
            }

        </li>
       
    </ul>

</div>


<h2>Listado de Entrevistas Vencidas</h2>
<table class="table table-striped table-condensed table-bordered">
        <tr>
            <th>Empleador</th>
            <th>Categoria</th>
            <th>Teléfono</th>
            <th>Postulante</th>
            <th>Fecha</th>
            <th>Vacante Cubierta</th>
            <th>Acciones</th>
        </tr>
    @foreach (var entrevista in Model.entrevistas)
    {
        <tr>
            <td>@entrevista.Oferta.Empleador.Apellido</td>
            <td>@entrevista.Oferta.Categoria.Descripcion</td>
            <td>@entrevista.Oferta.Empleador.Telefono</td>
            <td>@entrevista.Busqueda.Postulante.Apellido</td>
            
            <td>@entrevista.fechaEntrevista.ToString("dd/MM/yyyy")</td>
            <td>
                <div class="display-label" style="font-weight: normal">
                    @if (entrevista.cubreVacante)
                    {
                        <p>Si</p>
                    }
                    else
                    {
                        <p>No</p>
                    }

                </div>
            </td>
            
            <td>
                <a href="@Url.Action("Aprobar", "Entrevista", new { id = entrevista.entrevistaID })" class="btn" title="Marcar que cubre vacante"><span class="glyphicon glyphicon-thumbs-up"></span></a>
                <a href="@Url.Action("Desaprobar", "Entrevista", new { id = entrevista.entrevistaID })" class="btn" title="Marcar que no cubre vacante"><span class="glyphicon glyphicon-thumbs-down"></span></a>
                <a href="@Url.Action("Desctivar", "Oferta", new { id = entrevista.Oferta.OfertaID })" class="btn" title="Desactivar Oferta"><span class="glyphicon glyphicon-pencil"></span></a>
            </td>
        </tr>
        
    }
</table>

<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("ListarEntrevistasVencidas", new { page= x}))
</div>