Vicaria.WebUI/Controllers/EmpleadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;
using Vicaria.WebUI.Models;
using System.Collections.Specialized;
using System.Data.Entity.Validation;

namespace Vicaria.WebUI.Controllers
{
    public class EmpleadorController : Controller
    {
        private IEmpleadorRepository repository;
        public int PageSize = 100; //tamaño de página de la grilla de postulantes

        public EmpleadorController(IEmpleadorRepository empleadorRepository)
        {
            this.repository = empleadorRepository;
        }

        public ViewResult Borrar(int Id)
        {
            Empleador empleador = repository.Empleadores.FirstOrDefault(p => p.EmpleadorID == Id);
            return View(empleador);
        }

        [HttpPost]
        public ActionResult Borrar(Empleador empleador)
        {
            Empleador empleadorBorrado = repository.BorrarEmpleador(empleador.EmpleadorID);
            if (empleadorBorrado != null)
            {
                TempData["message"] = string.Format("{0} fué borrado", empleadorBorrado.Apellido);
            }
            return RedirectToAction("List");
        }

        public ViewResult Crear()
        {
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            Empleador empleador = new Empleador();
            empleador.FechaAlta = DateTime.Now;
            empleador.keepAlive = DateTime.Now;
            return View("Editar", empleador);
        }

        public ViewResult List(int page = 1)
        {
            EmpleadorListViewModel model = new EmpleadorListViewModel
            {
                Empleadores = repository.Empleadores
                    .OrderByDescending(p => p.keepAlive)
                    .Skip((page-1) * PageSize)
                    .Take(PageSize),
                    PagingInfo = new PagingInfo{
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = repository.Empleadores.Count()
                    }
            };
            return View(model);
        }

        public ViewResult Buscar( string busqueda, int page = 1) 
        {
            EmpleadorListViewModel model = new EmpleadorListViewModel();

            int dni = 0;
            bool esDni = int.TryParse(busqueda, out dni);
            
           
                if (esDni )
                {
                    model = new EmpleadorListViewModel
                    {
                        Empleadores = repository.Empleadores
                            .Where(e => e.Documento == dni)
                            .OrderByDescending(p => p.keepAlive)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize),
                        PagingInfo = new PagingInfo
                        {
                            CurrentPage = page,
                            ItemsPerPage = PageSize,
                            TotalItems = repository.Empleadores.Where(e => e.Documento == dni).Count()
                        }
                    };

                }
                else
                {
                    model = new EmpleadorListViewModel
                    {
                        Empleadores = repository.Empleadores
                            .Where(e => e.Apellido.ToUpper().Contains(busqueda.ToUpper()) || e.Nombre.ToUpper().Contains(busqueda.ToUpper()))
                            .OrderByDescending(p => p.keepAlive)
                            .Skip((page - 1) * PageSize)
                            .Take(PageSize),
                        PagingInfo = new PagingInfo
                        {
                            CurrentPage = page,
                            ItemsPerPage = PageSize,
                            TotalItems = repository.Empleadores.Where(e => e.Apellido.Contains(busqueda)).Count()
                        }
                    };


                };
             return View("List",model);



            





            }
           
       

       

        public ViewResult Editar(int Id)
        {
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            Empleador empleador = repository.Empleadores.FirstOrDefault(p => p.EmpleadorID == Id);
            return View(empleador);
        }
        
        [HttpPost]
        public ActionResult Editar(Empleador empleador)
        {
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            if (ModelState.IsValid)
            {
                repository.GrabarEmpleador(empleador);
                TempData["message"] = string.Format("{0} fué grabado corretamente", empleador.Apellido);
                return RedirectToAction("List");
            }
            else
            {
                //algo salio malo en os datos
                return View(empleador);
            }
        }

        public ViewResult Detallar(int Id, int retorno = 0)
        {

            Empleador empleador = repository.Empleadores.FirstOrDefault(p => p.EmpleadorID == Id);

            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "ID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            ViewBag.Retorno = retorno;

            return View(empleador);
        }

        public ActionResult KeepAlive(int Id)
        {
            Empleador empleador = repository.Empleadores.FirstOrDefault(p => p.EmpleadorID == Id);
            empleador.keepAlive = DateTime.Now;
            if (ModelState.IsValid)
            {
                repository.GrabarEmpleador(empleador);
                TempData["message"] = string.Format("{0} fué refrescado corretamente", empleador.Apellido);
                return RedirectToAction("List");
            }
            else
            {
                //algo salio malo en os datos
                return View(empleador);
            }
        }
    }
}

Vicaria.WebUI/Controllers/PostulanteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;
using Vicaria.WebUI.Models;
using System.Collections.Specialized;

namespace Vicaria.WebUI.Controllers
{
    public class PostulanteController : Controller
    {
        private IPostulanteRepository repository;
        public int PageSize = 100; //tamaño de página de la grilla de postulantes

        public PostulanteController(IPostulanteRepository postulanteRepository)
        {
            this.repository = postulanteRepository;
        }

        public ViewResult Borrar(int Id)
        {
            Postulante postulante = repository.Postulantes.FirstOrDefault(p => p.PostulanteID == Id);
            return View(postulante);
        }

        [HttpPost]
        public ActionResult Borrar(Postulante postulante)
        {
            Postulante postulannteBorrado = repository.BorrarPostulante(postulante.PostulanteID);
            if (postulannteBorrado != null)
            {
                TempData["message"]=string.Format("{0} fué borrado", postulannteBorrado.Apellido);
            }
            return RedirectToAction("List");
        }

        public ActionResult KeepAlive(int Id)
        {
            Postulante postulante = repository.Postulantes.FirstOrDefault(p => p.PostulanteID == Id);
            postulante.KeepAlive = DateTime.Now;
            if (ModelState.IsValid)
            {
                repository.GrabarPostulante(postulante);
                TempData["message"] = string.Format("{0} fué refrescado corretamente", postulante.Apellido);
                return RedirectToAction("List");
            }
            else
            {
                //algo salio malo en os datos
                return View(postulante);
            }
        }

        public ViewResult Crear()
        {
            ViewBag.Lista = new SelectList(repository.EstadosCiviles, "EstadoCivilId", "Descripcion");
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Nacionalidades = new SelectList(repository.Nacionalidades, "NacionalidadId", "Descripcion");
            ViewBag.Estudios = new SelectList(repository.Estudios, "EstudioCursadoID", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            ViewBag.GruposFamiliares = new SelectList(repository.GruposFamiliares, "GrupoFamiliarID", "Descripcion");
            Postulante postulante = new Postulante();
            postulante.FechaDeNacimiento = DateTime.Now;
            postulante.KeepAlive = DateTime.Now;
            postulante.FechaAlta = DateTime.Now;
            return View("Editar", postulante);
        }

        public ViewResult List(int page = 1)
        {
            PostulanteListViewModel model = new PostulanteListViewModel
            {
                Postulantes = repository.Postulantes
                    .OrderByDescending(p => p.KeepAlive)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Postulantes.Count()
                }

            };
            return View(model);
        }




        public ViewResult Buscar(string Busqueda, int page = 1)
        {
            PostulanteListViewModel model = new PostulanteListViewModel();

            int dni = 0;
            bool esDni = int.TryParse(Busqueda, out dni);
            if (esDni)
            {
                model = new PostulanteListViewModel
                {
                    Postulantes = repository.Postulantes
                        .Where(p => p.Documento == dni)
                        .OrderByDescending(p => p.KeepAlive)
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = repository.Postulantes.Where(p => p.Documento == dni).Count()
                    }
                };
            }
            else
            {
                 model = new PostulanteListViewModel
                {
                    Postulantes = repository.Postulantes
                        .Where(e => e.Apellido.ToUpper().Contains(Busqueda.ToUpper()) || e.Nombre.ToUpper().Contains(Busqueda.ToUpper()))
                        .OrderByDescending(p => p.KeepAlive)
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalItems = repository.Postulantes.Where(p => p.Apellido.Contains(Busqueda)).Count()
                    }
                };
            }

            return View("List", model);
        }

        public ViewResult Editar(int Id)
        {
            ViewBag.Lista = new SelectList(repository.EstadosCiviles, "EstadoCivilId", "Descripcion");
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Nacionalidades = new SelectList(repository.Nacionalidades, "NacionalidadID", "Descripcion");
            ViewBag.Estudios = new SelectList(repository.Estudios, "EstudioCursadoId", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            ViewBag.GruposFamiliares = new SelectList(repository.GruposFamiliares, "GrupoFamiliarID", "Descripcion");
            Postulante postulante = repository.Postulantes.FirstOrDefault(p => p.PostulanteID == Id);
            return View(postulante);
        }
        
        [HttpPost]
        public ActionResult Editar(Postulante postulante)
        {
            ViewBag.Lista = new SelectList(repository.EstadosCiviles, "EstadoCivilId", "Descripcion");
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "TipoDeDocumentoID", "Descripcion");
            ViewBag.Nacionalidades = new SelectList(repository.Nacionalidades, "NacionalidadID", "Descripcion");
            ViewBag.Estudios = new SelectList(repository.Estudios, "EstudioCursadoId", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            ViewBag.GruposFamiliares = new SelectList(repository.GruposFamiliares, "GrupoFamiliarID", "Descripcion");
            if (ModelState.IsValid)
            {
                repository.GrabarPostulante(postulante);
                TempData["message"] = string.Format("{0} fué grabado corretamente", postulante.Apellido);
                return RedirectToAction("List");
            }
            else
            {
                //algo salio malo en os datos
                return View(postulante);
            }
        }

        public ViewResult Detallar(int Id, int retorno = 0){
        
            Postulante postulante = repository.Postulantes.FirstOrDefault(p => p.PostulanteID == Id);

            ViewBag.Lista = new SelectList(repository.EstadosCiviles, "EstadoCivilId", "Descripcion");
            ViewBag.Documentos = new SelectList(repository.TiposDeDocumentos, "ID", "Descripcion");
            ViewBag.Nacionalidades = new SelectList(repository.Nacionalidades, "NacionalidadId", "Descripcion");
            ViewBag.Estudios = new SelectList(repository.Estudios, "EstudioCursadoId", "Descripcion");
            ViewBag.Provincias = new SelectList(repository.Provincias, "ProvinciaID", "Nombre");
            ViewBag.GruposFamiliares = new SelectList(repository.GruposFamiliares, "GrupoFamiliarID", "Descripcion");
            ViewBag.Retorno = retorno;

            return View(postulante);
        }


        public object model { get; set; }
    }
}

Vicaria.WebUI/Views/Postulante/Borrar.cshtml
@model Vicaria.Domain.Entities.Postulante
@{
    ViewBag.Title = "Borrar " + @Model.Nombre + " " + @Model.Apellido;
    //Layout = null;
}



<div class="panel">
    <div class="panel-heading">
        <h3>Borrar Postulante</h3>
        <div class="alert alert-warning">Si presiona borrar, este postulante será eliminado de la base de datos</div>
    </div>
    @using (Html.BeginForm("Borrar", "Postulante"))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.PostulanteID)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "PostulanteID")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Busqueda")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }
        </div>
        <div class="panel-footer">
            <input type="submit" value="Borrar" class="btn btn-primary" />
            <a href="@Url.Action("List", "Postulante")" class="btn">Cancelar y volver a postulantes <span class="glyphicon glyphicon-user"></span></a>
        </div>
    }

Vicaria.WebUI/Views/Postulante/Detallar.cshtml
@model Vicaria.Domain.Entities.Postulante

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría de Devoto</a>
</div>
<div class="panel">
    <div class="panel-heading">
        <h3>Detallar Postulante</h3>
    </div>
    <div class="panel-body">
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Apellido)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Apellido)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TipoDeDocumento)

                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TipoDeDocumento.Descripcion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Documento)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Documento)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FechaDeNacimiento)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FechaDeNacimiento)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Nacionalidad)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nacionalidad.Descripcion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EstadoCivil)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EstadoCivil.Descripcion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Direccion)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Direccion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Localidad)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Localidad)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Provincia)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Provincia.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Telefono)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Telefono)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Celular)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Celular)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Mail)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Mail)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.GrupoFamiliar)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.GrupoFamiliar.Descripcion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EspecializacionLaboral)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EspecializacionLaboral)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EstudioCursado)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EstudioCursado.Descripcion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DetalleDeEstudio)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DetalleDeEstudio)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ComoSeEntero)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ComoSeEntero)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Referencias)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Referencias)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Observaciones)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Observaciones)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Titulo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Titulo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.EstudiosTerminados)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EstudiosTerminados)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CV)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CV)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Idioma)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Idioma)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Informatica)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Informatica)
                </dd>

            </dl>
        </div>
    <div class="panel-footer">


        
        @{
            if (ViewBag.Retorno == 1)
            {
                <a class="bottomNav" onclick="history.go(-1); return false;" href="#" >Volver a posibles enlaces <span class="glyphicon glyphicon-bullhorn"></span></a>
            }
            else
            {
                <a href="@Url.Action("List", "Postulante")" class="btn">Volver a postulantes <span class="glyphicon glyphicon-user"></span></a>
            }

}
    </div>


Vicaria.WebUI/Views/Postulante/List.cshtml
@using Vicaria.WebUI.HtmlHelpers;
@model Vicaria.WebUI.Models.PostulanteListViewModel

@{
    ViewBag.Title = "Postulantes";
}

<div class="navbar navbar-inverse" role="navigation">
    <a class="navbar-brand" href="#">Criscarem - Vicaría de Devoto</a>
    <ul class="nav navbar-nav">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <input type="submit" value="Home" class="btn btn-default btn-lg ">
            }
        </li>
       
        <li>
            @using (Html.BeginForm("List", "Empleador"))
            {
                <input type="submit" value="Empleadores" class="btn btn-primary btn-lg">
            }

        </li>
        <li>
            @using (Html.BeginForm("ListarEntrevistas", "Entrevista"))
            {
                <input type="submit" value="Entrevistas" class="btn btn-warning btn-lg" />
            }

        </li>

    </ul>
</div>
<h2>Listado de postulantes</h2>

@*<a href="@Url.Action("Buscar", "Postulante")" class="btn-lg" title="Agregar Postulante"><span class="glyphicon glyphicon-search"></span></a>*@
@using (Html.BeginForm("Buscar", "Postulante"))
{
    


    <div class="dl-horizontal">
        <dt>
            <a href="@Url.Action("Crear", "Postulante")" class="btn-lg" title="Agregar Postulante">
                <span class="glyphicon glyphicon-plus-sign"></span>
                <input type="submit" value="Buscar" title="Buscar Postulante por documento">
            </a>
        </dt>
        <dd>
            <p>
               @Html.TextBox("Busqueda", null, new { @class = "form-control", style = "width:200px;", Value = "" })
            </p>
        </dd>
    </div>
        }
        @*<table class="table table-striped table-condensed table-bordered">*@
    <table class="table table-condensed" style="border-collapse:collapse;">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Teléfono</th>
                <th>Búsqueda</th>
                <th>Ingresado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model.Postulantes)
        {
            <tr data-toggle="collapse" data-target="#@p.Documento" class="accordion-toggle">
                <td >@p.Nombre</td>
                <td >@p.Apellido</td>
                <td >
                    @if (p.Telefono != null && p.Celular != null)
                {
                    @("Fijo:" + p.Telefono + "  Cel:" + p.Celular);
            }
            else
            {
                if (p.Telefono != null && p.Celular == null)
                {
                    @("Fijo:" + p.Telefono)
            }
            else
            {
                if (p.Telefono == null && p.Celular != null)
                {
                    @("Cel:" + p.Celular)
            }
        }

    }
                </td>

                @if (p.Busquedas.Count == 0 || p.Busquedas.First().Categoria == null)
            {
                <td>Sin búsqueda</td>
        }
        else
        {
            <td>@p.Busquedas.First().Categoria.Descripcion</td>
    }
                <td>@p.FechaAlta.ToString("dd/MM/yyyy")</td>
                <td width="20%">

                    <a href="@Url.Action("Editar", "Postulante", new { id = p.PostulanteID })" class="btn" title="Editar"><span class="glyphicon glyphicon-pencil"></span> </a>
                    <a href="@Url.Action("Detallar", "Postulante", new { id = p.PostulanteID })" class="btn" title="Ver"><span class="glyphicon glyphicon-eye-open"></span></a>
                    @*<a href="@Url.Action("Borrar", "Postulante", new { id = p.PostulanteID })" class="btn"><span class="glyphicon glyphicon-remove-circle"></span></a>*@
                    <a href="@Url.Action("ListaBusquedas", "Busqueda", new { id = p.PostulanteID, nombre = p.Apellido+" "+p.Nombre })" class="btn" title="ir a Búsquedas"><span class="glyphicon glyphicon-search"></span></a>
                    <a href="@Url.Action("ListarEntrevistasDePostulante", "Entrevista", new { idPostulante = p.PostulanteID })" class="btn" title="Entrevistas de postulante"><span class="glyphicon glyphicon-comment"></span></a>
                    <a href="@Url.Action("KeepAlive", "Postulante", new { id = p.PostulanteID })" class="btn" title="Mantener vivo"><span class="glyphicon glyphicon-heart"></span></a>
                </td>
            </tr>
            <tr>
                <td colspan="5" class="hiddenRow">
                
                    <div class="accordian-body collapse" id="@p.Documento">
                        @if (p.Entrevistas.Count() == 0 )  {
                    <p class="text-danger">No hay datos de entrevistas para este postulante</p>
}
else
{
                    <table class="table table-inverse" >

                                <thead>
                                    <tr>
                                        <th class="alert-info">Categoría</th>
                                        <th class="alert-info">Jornada</th>
                                        <th class="alert-info">Vacantes</th>
                                        <th class="alert-info">Empleador</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var e in p.Entrevistas)
        {
                            <tr>
                                <td class="text-primary"   >
                                     @e.Oferta.Categoria.Descripcion
                                </td>
                                <td class="text-primary">
                                    @e.Oferta.JornadaLaboral.Descripcion
                                </td>
                                <td class="text-primary">
                                    @e.Oferta.Vacantes
                                </td>
                                <td class="text-primary">
                                    @e.Oferta.Empleador.Apellido,  @e.Oferta.Empleador.Nombre
                                </td>
                                
                            </tr>

}
                                </tbody>
                            </table>
}
                    </div>
                
                </td>
        </tr>
}
            </tbody>
        </table>

        <div>
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x }))
        </div>
