Vicaria.WebUI/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;

namespace Vicaria.WebUI.Controllers
{
    public class CategoriaController : Controller
    {
        private ICategoriasRepository repository;

        public CategoriaController(ICategoriasRepository repo)
        {
            repository = repo;
        }

        public ActionResult ListarCategorias()
        {
            return View(repository.Categorias);
        }

        public ViewResult EditarCategoria(int Id)
        {
            Categoria categoria = repository.Categorias.FirstOrDefault(x => x.CategoriaID == Id);
            return View(categoria);
        }

        [HttpPost]
        public ActionResult EditarCategoria(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                repository.GrabarCategoria(categoria);
                TempData["message"] = string.Format("{0} fué grabado corretamente", categoria.Descripcion);
                return RedirectToAction("ListarCategorias");
            }
            else
            {
                //alg salio malo en os datos
                return View(categoria);
            }
        }

        public ViewResult CrearCategoria()
        {
            return View("EditarCategoria", new Categoria());
        }

        public ViewResult BorrarCategoria(int Id)
        {
            Categoria categoria = repository.Categorias.FirstOrDefault(p => p.CategoriaID == Id);
            return View(categoria);
        }

        [HttpPost]
        public ActionResult BorrarCategoria(Categoria categoria)
        {
            Categoria categoriaBorrada = repository.BorrarCategoria(categoria.CategoriaID);
            if (categoriaBorrada != null)
            {
                TempData["message"] = string.Format("{0} fué borrado", categoriaBorrada.Descripcion);
            }
            return RedirectToAction("ListarCategorias");
        }
    }
}

Vicaria.WebUI/Controllers/DocumentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;

namespace Vicaria.WebUI.Controllers
{
    public class DocumentoController : Controller
    {
        private IDocumentosRepository repository;

        public DocumentoController(IDocumentosRepository repo)
        {
            repository = repo;
        }

        public ActionResult ListarDocumentos()
        {
            return View(repository.TiposDeDocumentos);
        }

        public ViewResult EditarDocumento(int Id)
        {
            TipoDeDocumento documento = repository.TiposDeDocumentos.FirstOrDefault(x => x.TipoDeDocumentoID == Id);
            return View(documento);
        }

        [HttpPost]
        public ActionResult EditarDocumento(TipoDeDocumento tipoDeDocumento)
        {
            if (ModelState.IsValid)
            {
                repository.GrabarDocumento(tipoDeDocumento);
                TempData["message"] = string.Format("{0} fué grabado corretamente", tipoDeDocumento.Descripcion);
                return RedirectToAction("ListarDocumentos");
            }
            else
            {
                //alg salio malo en os datos
                return View(tipoDeDocumento);
            }
        }

        public ViewResult CrearDocumento()
        {
            return View("EditarDocumento", new TipoDeDocumento());
        }

        public ViewResult BorrarDocumento(int Id)
        {
            TipoDeDocumento tipoDeDocumento = repository.TiposDeDocumentos.FirstOrDefault(p => p.TipoDeDocumentoID == Id);
            return View(tipoDeDocumento);
        }

        [HttpPost]
        public ActionResult BorrarDocumento(TipoDeDocumento tipoDeDocumento)
        {
            TipoDeDocumento documentoBorrado = repository.BorrarDocumento(tipoDeDocumento.TipoDeDocumentoID);
            if (documentoBorrado != null)
            {
                TempData["message"] = string.Format("{0} fué borrado", documentoBorrado.Descripcion);
            }
            return RedirectToAction("ListarDocumentos");
        }
    }
}

Vicaria.WebUI/Controllers/EdadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;

namespace Vicaria.WebUI.Controllers
{
    public class EdadController : Controller
    {
       private IEdadRepository repository;

       public EdadController(IEdadRepository repo)
        {
            repository = repo;
        }

        public ActionResult ListarEdades()
        {
            return View(repository.Edades);
        }

        public ViewResult EditarEdad(int Id)
        {
            Edad edad = repository.Edades.FirstOrDefault(x => x.EdadID == Id);
            return View(edad);
        }

        [HttpPost]
        public ActionResult EditarEdad(Edad edad)
        {
            if (ModelState.IsValid)
            {
                repository.GrabarEdad(edad);
                return RedirectToAction("ListarEdades");
            }
            else
            {
                //alg salio malo en os datos
                return View(edad);
            }
        }

        public ViewResult CrearEdad()
        {
            return View("EditarEdad", new Edad ());
        }

        public ViewResult BorrarEdad(int Id)
        {
            Edad edad = repository.Edades.FirstOrDefault(p => p.EdadID == Id);
            return View(edad);
        }

        [HttpPost]
        public ActionResult BorrarEdad(Edad edad)
        {
            Edad edadBorrada = repository.BorrarEdad(edad.EdadID);
            if (edadBorrada != null)
            {
                TempData["message"] = string.Format("El rango desde {0} hasta {1} fué borrado", edadBorrada.Desde, edadBorrada.Hasta);
            }
            return RedirectToAction("ListarEdades");
        }
    }
}

Vicaria.WebUI/Controllers/EstudioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vicaria.Domain.Abstract;
using Vicaria.Domain.Entities;

namespace Vicaria.WebUI.Controllers
{
    public class EstudioController : Controller
    {
        private IEstudiosRepository repository;

        public EstudioController(IEstudiosRepository repo)
        {
            repository = repo;
        }

        public ActionResult ListarEstudiosCursados()
        {
            return View(repository.EstudiosCursados);
        }

        public ViewResult EditarEstudioCursado(int Id)
        {
            EstudioCursado estudioCursado = repository.EstudiosCursados.FirstOrDefault(x => x.EstudioCursadoID == Id);
            return View(estudioCursado);
        }

        [HttpPost]
        public ActionResult EditarEstudioCursado(EstudioCursado estudioCursado)
        {
            if (ModelState.IsValid)
            {
                repository.GrabarEstudioCursado(estudioCursado);
                TempData["message"] = string.Format("{0} fué grabado corretamente", estudioCursado.Descripcion);
                return RedirectToAction("ListarEstudiosCursados");
            }
            else
            {
                //alg salio malo en os datos
                return View(estudioCursado);
            }
        }

        public ViewResult CrearEstudioCursado()
        {
            return View("EditarEstudioCursado", new EstudioCursado());
        }

        public ViewResult BorrarEstudioCursado(int Id)
        {
            EstudioCursado estudioCursado = repository.EstudiosCursados.FirstOrDefault(p => p.EstudioCursadoID == Id);
            return View(estudioCursado);
        }

        [HttpPost]
        public ActionResult BorrarEstudioCursado(EstudioCursado estudioCursado)
        {
            EstudioCursado estudioCursadoBorrado = repository.BorrarEstudioCursado(estudioCursado.EstudioCursadoID);
            if (estudioCursadoBorrado != null)
            {
                TempData["message"] = string.Format("{0} fué borrado", estudioCursadoBorrado.Descripcion);
            }
            return RedirectToAction("ListarEstudiosCursados");
        }
    }
}

Vicaria.WebUI/Views/Shared/Date.cshtml
@model DateTime
@Html.TextBox("", String.Format("{0:d}", Model.ToShortDateString()),
  new { @class = "datefield", type = "date" })

Vicaria.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>

<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Criscarem - Vicaría</a>
        <ul class="nav navbar-nav">
           
            <li>
                @using (Html.BeginForm("Index", "EstadoCivil"))
                {
                    <input type="submit" value="Estado Civil" class="btn btn-default navbar-btn">
                }
            </li> 
            
            <li>
                @using (Html.BeginForm("ListarEstudiosCursados", "Estudio"))
                {
                    <input type="submit" value="Estudio" class="btn btn-default navbar-btn">
                }
            </li>
            <li>
                @using (Html.BeginForm("ListarNacionalidades", "Nacionalidad"))
                {
                    <input type="submit" value="Nacionalidad" class="btn btn-default navbar-btn">
                }
            </li>
            <li>
                @using (Html.BeginForm("ListarProvincias", "Provincia"))
                {
                    <input type="submit" value="Provincia" class="btn btn-default navbar-btn">
                }
            </li>
            <li>
                @using (Html.BeginForm("ListarDocumentos", "Documento"))
                {
                    <input type="submit" value="Documento" class="btn btn-default navbar-btn">
                }
            </li>
            <li>
                @using (Html.BeginForm("ListarGruposFamiliares", "GrupoFamiliar"))
                {
                    <input type="submit" value="Grupo Familiar" class="btn btn-default navbar-btn">
                }
            </li>
            <li>
                @using (Html.BeginForm("ListarCategorias", "Categoria"))
                {
                    <input type="submit" value="Categoria" class="btn btn-default navbar-btn">
                }
            </li>
            <li>
                @using (Html.BeginForm("ListarJornadasLaborales", "JornadaLaboral"))
                {
                    <input type="submit" value="Jornada Laboral" class="btn btn-default navbar-btn">
                }
            </li>
            @*<li>
                @using (Html.BeginForm("ListarEdades", "Edad"))
                {
                    <input type="submit" value="Edades" class="btn btn-default navbar-btn">
                }
            </li>*@

            <li>
                @using (Html.BeginForm("ListarContrataciones", "Contratacion"))
                {
                    <input type="submit" value="Contratación" class="btn btn-default navbar-btn">
                }
            </li>
            <li>
                @using (Html.BeginForm("Index", "Home"))
                {
                    <input type="submit" value="Home" class="btn btn-default navbar-btn">
                }
            </li>
           
            
         </ul>

</div>
    
    

        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
    </div>
    <div>
        @RenderBody()
    </div>
       
    
    
    
    
    
</body>
</html>

Vicaria.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")"
          rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")"
          rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")"
          rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery.ui.core.min.js")"
            type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")"
            type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/DatePickerReady.js")"
            type="text/javascript"></script>

    <title>@ViewBag.Title</title>
</head>
<body>
    @*<div class="navbar " role="navigation">
        
        <a class="navbar-brand" href="#">
            Vicaria de Devoto
        </a>
    </div>
    <ol class="breadcrumb">
        <li><a href="#">Inicio</a></li>
        
    </ol>*@
   
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
    </div>

    <div class="container body-content">
        @RenderBody()
       
        
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>